"""create dogs and worklogs tables

Revision ID: c60101667382
Revises: 
Create Date: 2026-03-14 18:33:21.109470
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60101667382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('main_role', sa.String(length=50), nullable=True),
    sa.Column('kennel_row', sa.String(length=50), nullable=True),
    sa.Column('home_slot', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_id'), 'dogs', ['id'], unique=False)
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=True)
    op.create_table('worklogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('week_label', sa.String(length=20), nullable=True),
    sa.Column('km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('worked', sa.Boolean(), nullable=False),
    sa.Column('programs_10km', sa.Integer(), nullable=False),
    sa.Column('programs_3km', sa.Integer(), nullable=False),
    sa.Column('kennel_row', sa.String(length=50), nullable=True),
    sa.Column('home_slot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('main_role', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dog_id', 'work_date', name='uq_worklog_dog_date')
    )
    op.create_index(op.f('ix_worklogs_dog_id'), 'worklogs', ['dog_id'], unique=False)
    op.create_index(op.f('ix_worklogs_id'), 'worklogs', ['id'], unique=False)
    op.create_index(op.f('ix_worklogs_work_date'), 'worklogs', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worklogs_work_date'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_id'), table_name='worklogs')
    op.drop_index(op.f('ix_worklogs_dog_id'), table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_id'), table_name='dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
